### ISSUE TITLE
scratchGet returns nothing

### ISSUE THREAD

**Issue by amazinigmech2418** [kyleplo/scratchOn#11]

**Comment by kyleplo** [comment]
What is the full code?

**Comment by amazinigmech2418** [comment]
`scratchOn.scratchGet("/projects","/237042475","/internal-api","get")` I know this won't really return any info, but it doesn't return anything and has no error.

**Comment by kyleplo** [comment]
When I did that, this is what the console said:
![image](https://user-images.githubusercontent.com/31634240/43518299-a0dd2038-9559-11e8-926f-25c5905195ac.png)

### Two things I'm not sure you understand
1. Adding the `await` keyword will make it wait for the Promise to finish, instead of returning the Promise.
2. This is running by default on `https://api.scratch.mit.edu`. To switch it to `https://scratch.mit.edu`, use `scratchOn.api = "https://scratch.mit.edu"`
